---
- block:
  - name: Create SSL directory
    file:
      path: "{{ ssl_dir_path }}"
      state: directory
      owner: root
      group: root
      mode: '0755'

  - copy:
      content: "{{ vault_ssl_certificate_key }}"
      dest: "{{ ssl_certificate_key_path }}"
      owner: root
      group: root
      mode: '0600'
  
  - copy:
      content: "{{ vault_ssl_certificate }}"
      dest: "{{ ssl_certificate_path }}"
      owner: root
      group: root
      mode: '0640'

  tags:
    - cert-vault
  notify: restart nginx

