---
# handlers file for ansible-role-jenkins
- name: reload systemd
  ansible.builtin.command: systemctl daemon-reload
  become: true

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart jenkins
  service:
    name: jenkins
    state: restarted

